import './sass/main.scss';
import './js/modal-film-card.js';
import './js/modal-window-team.js';
import './js/spiner';
import './js/pagination.js';
import './js/popular';
import './js/getSearchFilm.js';
import './js/scrollTop';
// import './js/firebaseGoogAuth';
import './js/them.js';